#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App2.Resource", IsApplication=true)]

namespace App2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int black = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int dategray = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int title = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int white = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int activity_horizontal_margin = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int activity_vertical_margin = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int account_down = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int account_up = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cap_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int close_down = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int close_up = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_list_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int edit_down = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int edit_up = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int EditTextStyle = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int mmsms_item_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int plus_down = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int plus_up = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int project_down = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int project_up = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int setup_down = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int setup_up = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sns_down = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int sns_up = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090002
			public const int account_list_view = 2131296258;
			
			// aapt resource value: 0x7f09000c
			public const int accountdescription = 2131296268;
			
			// aapt resource value: 0x7f090024
			public const int accountdone = 2131296292;
			
			// aapt resource value: 0x7f090000
			public const int accountout = 2131296256;
			
			// aapt resource value: 0x7f090003
			public const int accountplus = 2131296259;
			
			// aapt resource value: 0x7f09000a
			public const int accountprice = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int accounttitle = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int addaccountout = 2131296263;
			
			// aapt resource value: 0x7f09000d
			public const int addaccountresult = 2131296269;
			
			// aapt resource value: 0x7f090050
			public const int addsnsout = 2131296336;
			
			// aapt resource value: 0x7f090051
			public const int addsnsresult = 2131296337;
			
			// aapt resource value: 0x7f090015
			public const int addtaskresult = 2131296277;
			
			// aapt resource value: 0x7f090010
			public const int addtitle = 2131296272;
			
			// aapt resource value: 0x7f090008
			public const int addtitlelayout = 2131296264;
			
			// aapt resource value: 0x7f09000b
			public const int check = 2131296267;
			
			// aapt resource value: 0x7f090022
			public const int commentbtn = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int commenttext = 2131296289;
			
			// aapt resource value: 0x7f090016
			public const int confirm = 2131296278;
			
			// aapt resource value: 0x7f09001f
			public const int contents = 2131296287;
			
			// aapt resource value: 0x7f09002e
			public const int createdate = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int deadline = 2131296303;
			
			// aapt resource value: 0x7f090028
			public const int deleteaccount = 2131296296;
			
			// aapt resource value: 0x7f09004c
			public const int donebtn = 2131296332;
			
			// aapt resource value: 0x7f090027
			public const int editaccountdescription = 2131296295;
			
			// aapt resource value: 0x7f090023
			public const int editaccountout = 2131296291;
			
			// aapt resource value: 0x7f090026
			public const int editaccountprice = 2131296294;
			
			// aapt resource value: 0x7f090025
			public const int editaccounttitle = 2131296293;
			
			// aapt resource value: 0x7f09004d
			public const int editsnsout = 2131296333;
			
			// aapt resource value: 0x7f09004f
			public const int editsnsresult = 2131296335;
			
			// aapt resource value: 0x7f090048
			public const int edittitlelayout = 2131296328;
			
			// aapt resource value: 0x7f090049
			public const int edittitleresult = 2131296329;
			
			// aapt resource value: 0x7f09002c
			public const int edittitletext = 2131296300;
			
			// aapt resource value: 0x7f09001c
			public const int filecom = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int filelayout = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int filename = 2131296286;
			
			// aapt resource value: 0x7f090030
			public const int id = 2131296304;
			
			// aapt resource value: 0x7f090020
			public const int intasklist = 2131296288;
			
			// aapt resource value: 0x7f090005
			public const int isacccost = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int isaccdesc = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int isaccname = 2131296260;
			
			// aapt resource value: 0x7f090053
			public const int isfileCdate = 2131296339;
			
			// aapt resource value: 0x7f090054
			public const int isfiledata = 2131296340;
			
			// aapt resource value: 0x7f090052
			public const int isfileperson = 2131296338;
			
			// aapt resource value: 0x7f090056
			public const int ismenssionCdate = 2131296342;
			
			// aapt resource value: 0x7f090057
			public const int ismenssiondata = 2131296343;
			
			// aapt resource value: 0x7f090055
			public const int ismenssionperson = 2131296341;
			
			// aapt resource value: 0x7f090064
			public const int item1 = 2131296356;
			
			// aapt resource value: 0x7f090065
			public const int item2 = 2131296357;
			
			// aapt resource value: 0x7f090066
			public const int item3 = 2131296358;
			
			// aapt resource value: 0x7f090001
			public const int leave_account = 2131296257;
			
			// aapt resource value: 0x7f090034
			public const int linear_parent = 2131296308;
			
			// aapt resource value: 0x7f09003a
			public const int listview = 2131296314;
			
			// aapt resource value: 0x7f090032
			public const int loginbtn = 2131296306;
			
			// aapt resource value: 0x7f090045
			public const int mmsns_comment_view = 2131296325;
			
			// aapt resource value: 0x7f090044
			public const int mmsns_list_view = 2131296324;
			
			// aapt resource value: 0x7f090042
			public const int mmsnsout = 2131296322;
			
			// aapt resource value: 0x7f09004a
			public const int name = 2131296330;
			
			// aapt resource value: 0x7f09004b
			public const int number = 2131296331;
			
			// aapt resource value: 0x7f090031
			public const int pass = 2131296305;
			
			// aapt resource value: 0x7f090060
			public const int project_member = 2131296352;
			
			// aapt resource value: 0x7f09005f
			public const int project_name = 2131296351;
			
			// aapt resource value: 0x7f09002b
			public const int projecteditdone = 2131296299;
			
			// aapt resource value: 0x7f090047
			public const int projecteditout = 2131296327;
			
			// aapt resource value: 0x7f09002a
			public const int projectname = 2131296298;
			
			// aapt resource value: 0x7f090029
			public const int projectnameeditout = 2131296297;
			
			// aapt resource value: 0x7f090033
			public const int registerbtn = 2131296307;
			
			// aapt resource value: 0x7f090035
			public const int search = 2131296309;
			
			// aapt resource value: 0x7f090041
			public const int sns_body = 2131296321;
			
			// aapt resource value: 0x7f09003e
			public const int sns_comment_body = 2131296318;
			
			// aapt resource value: 0x7f09003d
			public const int sns_comment_day = 2131296317;
			
			// aapt resource value: 0x7f09003c
			public const int sns_comment_writer = 2131296316;
			
			// aapt resource value: 0x7f090040
			public const int sns_write_date = 2131296320;
			
			// aapt resource value: 0x7f09003f
			public const int sns_writer = 2131296319;
			
			// aapt resource value: 0x7f09004e
			public const int snsbody = 2131296334;
			
			// aapt resource value: 0x7f090043
			public const int snsedit = 2131296323;
			
			// aapt resource value: 0x7f090046
			public const int snsplus = 2131296326;
			
			// aapt resource value: 0x7f09002d
			public const int taksname = 2131296301;
			
			// aapt resource value: 0x7f090018
			public const int taskTitle = 2131296280;
			
			// aapt resource value: 0x7f090012
			public const int taskadddeadline = 2131296274;
			
			// aapt resource value: 0x7f09000e
			public const int taskaddout = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int taskaddstartline = 2131296273;
			
			// aapt resource value: 0x7f09001a
			public const int taskdeadline = 2131296282;
			
			// aapt resource value: 0x7f09005e
			public const int taskdelete = 2131296350;
			
			// aapt resource value: 0x7f090014
			public const int taskdescription = 2131296276;
			
			// aapt resource value: 0x7f090059
			public const int taskdone = 2131296345;
			
			// aapt resource value: 0x7f09001b
			public const int taskedit = 2131296283;
			
			// aapt resource value: 0x7f09005c
			public const int taskeditdeadline = 2131296348;
			
			// aapt resource value: 0x7f09005d
			public const int taskeditdescription = 2131296349;
			
			// aapt resource value: 0x7f090058
			public const int taskeditout = 2131296344;
			
			// aapt resource value: 0x7f09005b
			public const int taskeditstartline = 2131296347;
			
			// aapt resource value: 0x7f090013
			public const int taskfile = 2131296275;
			
			// aapt resource value: 0x7f090019
			public const int taskmaster = 2131296281;
			
			// aapt resource value: 0x7f09000f
			public const int taskname = 2131296271;
			
			// aapt resource value: 0x7f090017
			public const int taskout = 2131296279;
			
			// aapt resource value: 0x7f09003b
			public const int taskplus = 2131296315;
			
			// aapt resource value: 0x7f09005a
			public const int tasktitleresult = 2131296346;
			
			// aapt resource value: 0x7f090062
			public const int teamchange = 2131296354;
			
			// aapt resource value: 0x7f090063
			public const int teamlist = 2131296355;
			
			// aapt resource value: 0x7f090061
			public const int teamlist_close = 2131296353;
			
			// aapt resource value: 0x7f090037
			public const int toaccount = 2131296311;
			
			// aapt resource value: 0x7f090038
			public const int toproject = 2131296312;
			
			// aapt resource value: 0x7f090039
			public const int tosns = 2131296313;
			
			// aapt resource value: 0x7f090036
			public const int user = 2131296310;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int account_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Add_Account_Layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Add_Task_Layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int another_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int another_layout_nonfile = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Edit_Account_Layout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int EditTitle_layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int HeaderLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Inflated_layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LoginLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int mmsns_comment_layout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int mmsns_list_layout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int mmsns_list_layout_solo = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int mmsns_more_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int mmssns_layout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ProjectEditLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int register_layout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int sns_edit_layout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int sns_write_layout = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Task_file = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Task_menssion = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int TaskEditLayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int team_list = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int team_select_layout = 2130903065;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int popup_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_NoTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
